# Generated by Django 4.1.7 on 2023-04-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrega3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='creado_el',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='modificado_el',
        ),
    ]
