# Generated by Django 4.1.7 on 2023-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega3', '0002_rename_creado_el_articulo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
